### ISSUE TITLE
Publish module to public npm registry

### ISSUE THREAD

**Issue by jonathansamines** [salesforce-it/hapi-auth-signedrequest#1]
There is a reason why this module hasn´t been published to the publish npm registry? Are you planning to do that?

**Comment by AndyBean** [comment]
Good point and thanks for the reminder. We need to check into our open source guidelines and ensure it passes muster and will get the process started.

@rbirbeck @phitran

**Comment by jonathansamines** [comment]
Hi! any update on this?

**Comment by rbirbeck** [comment]
done!
